file = open("Codingal.txt","r")
print(file.read())
file.close()
file = open("Codingal.txt","r")
print("\n read in parts")
print(file.read(8))
file.close()
file = open("Codingal.txt","a")
file.write("hi i am Derion and i am 20 year old")
file.close()